### PR TITLE
Plugin architecture testing

### PR DESCRIPTION
**Pull request by clegaspi**
PR to test @shyamd 's plugin architecture from #187

### CODE REVIEW

**Comment by mkhorton** [comment]
This looks very nice. If tests pass (+ you've manually verified the web app works, which is doesn't have as good test coverage), I'd say merge :)

Thanks @shyamd !

**Comment by clegaspi** [comment]
I have a thought/question. Codacy is making a lot of noise about "unused imports", which result from the need to `import propnet.models` or `import propnet.symbols` before `from propnet.core.registry import Registry` in order for the registry to be populated.

To me, the need for both lines is somewhat unintuitive from a usability standpoint. Would it be better to:
1. Import the models and symbols in `propnet/__init__.py` so the registry is automatically populated, requiring the user to only import the registry.
2. Create some sort of alias/wrapper for `Registry("models")` and `Registry("symbols")` in the `propnet.models` and `propnet.symbols` modules, respectively, so the user only needs to import the alias.

Option 1 will take some doing, because simply calling `import propnet.[models/symbols]` at the top of `propnet/__init__.py` causes circular import errors. We can put it at the bottom of the file, but that seems like bad practice?

Option 2 feels like we're defeating the purpose of the registry in the first place.

@shyamd @mkhorton do you have thoughts? Or do you think the implementation is ok as is?
Thanks!

**Comment by shyamd** [comment]
It's also possible to mute those concerns in Codacy since this is a pattern we're trying to use.

**Comment by clegaspi** [comment]
Sure, right. I guess I was just concerned if this was the intention or just a result of how propnet is currently set up. Is this how you have implemented other such meta-class registries?

**Comment by shyamd** [comment]
The registry pattern is somewhat different in most other cases because our models and symbols would actually be part of a completely different package for most other situations. For propnet, this was the intended use case, to ensure that if you wanted the built in models and symbols, you had to explicitly import them, but could do that with a simple command.

**Pull request merged**
