### PR TITLE
 Plugin architecture

### PR DESCRIPTION
**Pull request by shyamd**
Work in progress pull request for a plugin architecture where Propnet knows about all models and symbols etc. This is so others can watch as the magic happens.

### CODE REVIEW

**Comment by shyamd** [comment]
So, I've been fighting the tests for the weekend. The basic issue is that various parts of the code such as the graph portion don't account for the fact that only one instance of a Model or Symbol should exist. 
Options:
1..) I can relax this so that you can instantiate mutiple model/symbol objects with the same name but either the first or last instance of that gets registered.
2.) I can update Graph/etc to be more resilient to the concept of only one model instance with a name, etc. but this will take a lot longer.

**Comment by clegaspi** [comment]
Hey Shyam,

I did some thinking about how we want to deal with duplicate model names. I think it would be best to require the user to manually unregister a model if they want to override it with their own. Does this make sense?

**Comment by shyamd** [comment]
This is ready to be merged.

Anyone can add in models and symbols by doing the following:
```
from propnet.core.registry import Registry

models = Registry("models")
symbols = Registry("symbols")

models["my_model"] = the_model
symbols["my_symbol"] = the_symbol
```

This way we can move the models and symbols around it won't break any plugin modules.

**Comment by clegaspi** [comment]
This looks good to me from what I can see. I changed the base branch to a branch on this repository so it can run the web and rester tests that it skips.

**Pull request merged**
