### PR TITLE
Model refactor

### PR DESCRIPTION
**Pull request by montoyjh**
This PR is primarily to track progress on some of the ways in which I'm refactoring models.  My goal is to simplify the class structure, the serialization format, and generally to lighten the load users (and devs) experience in making a propnet model.

### CODE REVIEW

**Comment by montoyjh** [comment]
My initial set of revisions sketch out a new class structure for Model, a rough serialization format for an entirely yaml based model, contained in models/serialized/band_gap_refractive_index.yaml, and a python-based model, contained in models/python/atomic_density.py.  My hope is that all of the prior functionality can be captured in a simplified class that can be instantiated from one or the other (propnet.core.model.Model) using mostly preexisting MSONable machinery.

**Comment by montoyjh** [comment]
Just wanted to comment here that I believe most of the code changes are done here, the functional tests are passing, and the remainder of the work is translating between the old/new formats.

**Comment by mkhorton** [comment]
Looks like a really nice refactor, I'd be happy to see this merged.

The only down-side I see is that in the new yaml serialization `description` is like any other key, which means extended descriptions will be a bit clunky / will have to follow yaml syntax requirements first (in terms of line breaks/indentation etc.), meaning it'll be a slightly awkward Markdown/yaml hybrid. This is in contrast to the previous style, which was yaml header front-matter and a Markdown description footer, which is admittedly a bit clunky in its own right, though has been used elsewhere in e.g. a lot of blogging/static site tools. Not sure what others think here.

Other than that minor comment, I'm on board with the changes. I like the separation of Model into PyModel, EquationModel etc. in particular, looks good!

**Comment by mkhorton** [comment]
Actually, one further comment -- has the parsing into the new format mangled the references? This is perhaps my fault for trying to be too clever with our reference handling, but the old format just had e.g. `doi:[a_doi]` as a reference, which would be parsed on the fly into bibtex + stored into a cache. It looks like the bibtex references are hard-coded now. This is fine though, the "doi:..." and "url:..." shorthand was really just to make it faster to implement a new model anyway, once we have the bibtex refs no reason we shouldn't just serialize them instead.

**Comment by mkhorton** [comment]
Yeah, I think that would be fine. It does make it a bit more awkward e.g. if you cut and paste from Markdown from elsewhere, or remember that indentation rules change (e.g. 6 spaces instead of 4 for a code block). Honestly don't think it's a big deal though, and sticking with pure yaml like in this PR does have its advantages too (e.g. can use monty).

**Comment by computron** [comment]
All - I won't have time to review this PR. Please merge when you are all in agreement.

I think in general, I will more give sporadic (e.g., once or twice a year) top-down code reviews rather than be able to follow and approve each PR - so please don't wait for me!

**Comment by montoyjh** [comment]
Okay, I've fixed references and done a bit of formatting.  There's still a bit of cleanup that could be done on the models to make them more uniform, but I'm going to merge once the tests pass.

**Comment by mkhorton** [comment]
Sounds good! Looks a lot cleaner as it is already

Happy to discuss reference issue offline btw if you think there's a better way of handling them (I don't really like requiring people to discover the "doi:" or "url:" syntax)

**Pull request merged**
