### PR TITLE
Relations between heat capacities 

### PR DESCRIPTION
**Pull request by jdagdelen**
RE issue #91

### CODE REVIEW

**Comment by jdagdelen** [comment]
I'm not sure why this is failing the tests. Why is specific_heat_capacity_constant_volume not found?

**Comment by mkhorton** [comment]
Thanks @jdagdelen !

Any thoughts on how we can get inputs for this model from MP data?

**Comment by jdagdelen** [comment]
Yeah, I believe we can get it from our phonons. http://www.ece.drexel.edu/mml/pubs/heatcapTi3GeC2.pdf

**Comment by jdagdelen** [comment]
There are also empirical models for heat capacity (Einstein and Debye models)

**Comment by mkhorton** [comment]
Are you interested in helping build up our phonon support and linking these models together? Note we already have Debye, but currently just getting Debye temp, not heat capacities.

**Comment by jdagdelen** [comment]
Yeah, I'm interested.

**Pull request merged**
